### ISSUE TITLE
Add tests using volttron-testing

### ISSUE THREAD

**Issue by bonicim** [eclipse-volttron/volttron-lib-modbustk-driver#1]
Port over [tests from modular volttron](https://github.com/VOLTTRON/volttron/tree/main/services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/tests), using the [volttron-testing library](https://github.com/VOLTTRON/volttron-testing)

**Comment by craig8** [comment]
The one test really doesn't do anything yet
