### ISSUE TITLE
Fix code scanning alert - Overly permissive regular expression range

### ISSUE THREAD

**Issue by craigpnnl** [eclipse-volttron/volttron-lib-modbustk-driver#4]
Tracking issue for:
- [ ] https://github.com/eclipse-volttron/volttron-lib-modbustk-driver/security/code-scanning/2

See if this can be less permissive for the regular expression.

**Comment by davidraker** [comment]
The regex was getting flagged because it used A-z instead of A-Z. This doesn't appear to have been intentional, since it also used the range a-z, and has thus been corrected.
