### ISSUE TITLE
Correct the context for the demoboard tests

### ISSUE THREAD

**Issue by craigpnnl** [eclipse-volttron/volttron-lib-modbustk-driver#5]
**Describe the bug**
Make the demo-board not run on github actions only locally.

You should be able to use an environmental variable to detect working on github actions.

**Comment by davidraker** [comment]
@craig8 This is already the case. The pytestmark global variable is set on test_driver_demo-board.py line 13 if the environment variable MODBUS_TEST_IP is not set.  Github does, incidentally, appear to be skipping these tests correctly. Am I missing something else?

**Comment by craigpnnl** [comment]
https://github.com/eclipse-volttron/volttron-lib-modbustk-driver/actions/workflows/run-tests.yml

**Comment by craigpnnl** [comment]
Looking at the tests mentioned above I see

tests/test_driver_demo_board.py ss                                       [ 50%]

Error: test_set_point[volttron_instance0]

volttron.utils.jsonrpc.RemoteError: builtins.TimeoutError('timed out')
tests/test_driver_local.py .F                                            [100%]

**Comment by craigpnnl** [comment]
and now that I see the ss 50% I will close this :)
